version: 0.1.{build}
configuration: Debug
install:
  - git clone https://github.com/akheron/jansson.git
  - cd jansson
  - autoreconf -i
  - ./configure
  - make
  - make install
  - cd ..
build_script:
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build .