version: 0.1.{build}
configuration: Debug
cache: c:\tools\vcpkg\installed\
install:
  - vcpkg install curl
  - vcpkg install jansson
  - vcpkg integrate install
build_script:
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_TOOLCHAIN_FILE=c:/tools/vcpkg/scripts/buildsystems/vcpkg.cmake
  - cmake --build .
